export const DomainEventCode = {
  TALK_ASSIGNED_FOR_REVIEW: 'TALK_ASSIGNED_FOR_REVIEW',
  SPEAKER_REGISTERED: 'SPEAKER_REGISTERED',
  SPEAKER_PROFILE_UPDATED: 'SPEAKER_PROFILE_UPDATED',
  TALK_PROPOSED: 'TALK_PROPOSED',
  SOMETHING_HAPPENED: 'SOMETHING_HAPPENED',
}

export type DomainEventCode = (typeof DomainEventCode)[keyof typeof DomainEventCode]
