name: CI

on:
  push:
    branches:
      - main

jobs:
  skip-draft:
    name: skip draft
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: fail on draft
        if: github.event.pull_request.draft == true
        run: echo "is a draft PR, failing..." && exit 1
      - name: success
        run: echo "is not a draft PR"

  tests:
    needs: skip-draft
    name: Lint & Test
    runs-on: ubuntu-latest
    container: node:lts
    timeout-minutes: 5
    services:
      database:
        image: postgres:14.1-alpine
        env:
          POSTGRES_USER: acid
          POSTGRES_PASSWORD: password
          POSTGRES_DB: develop
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Typecheck
        run: yarn typecheck
      - name: Eslint
        run: yarn lint:ci
      - name: Prettier
        run: yarn format:ci
      - name: Tests
        run: |
          yarn migration:run
          yarn test:ci
        env:
          DB_HOST: database
          DB_USERNAME: acid
          DB_PASSWORD: password
          DB_DATABASE: develop

  docker-build:
    needs: skip-draft
    name: Build Docker Container
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          tags: nestjs:latest
